### ISSUE TITLE
可否加个最小化的按钮

### ISSUE THREAD

**Issue by a145600** [li-zheng-hao/StikyNotes#14]
置顶后会有最小化的需求，反复开关置顶的话感觉有些emmm，望大佬考虑一下

**Comment by li-zheng-hao** [comment]
置顶为什么还要最小化？不好意思我没太搞懂你的意思。

**Comment by a145600** [comment]
置顶方便配合其他工具使用，当我不再需要观看的时候就会想隐藏起来专心做其他事情，这样子

**Comment by li-zheng-hao** [comment]
我觉得你可以不用置顶，想看的时候点一下托盘区的小图标就全部显示了。或者置顶后把标签移动到屏幕最上方也是会和QQ一样自动隐藏的。
